In [ ]:
import numpy as np

In [ ]:
A = np.array([[1,0,0,1],
              [0,1,0,2],
              [0,0,1,2],
              [1,2,2,0]])

In [ ]:
A.shape

(4, 4)

In [ ]:
b = np.array([0,0,0,1])

In [ ]:
b

array([0, 0, 0, 1])

In [ ]:
x = np.linalg.solve(A, b)

In [ ]:
x.round(3)

array([ 0.111,  0.222,  0.222, -0.111])

In [ ]:
0.111111 + 2*0.222222 + 2*0.222222

0.9999990000000001

In [ ]:
A1 = np.array([[6,2,1,1,0],
               [2,5,2,0,1],
               [1,2,4,1,0],
               [1,0,1,0,0],
               [0,1,0,0,0]])

In [ ]:
A1

array([[6, 2, 1, 1, 0],
       [2, 5, 2, 0, 1],
       [1, 2, 4, 1, 0],
       [1, 0, 1, 0, 0],
       [0, 1, 0, 0, 0]])

In [ ]:
b1 = np.array([-8,-3,-3,3,0])

In [ ]:
b1

array([-8, -3, -3,  3,  0])

In [ ]:
x = np.linalg.solve(A1, b1)

In [ ]:
x

array([  0.5,   0. ,   2.5, -13.5,  -9. ])

In [17]:
def f(x, y):
    return 10*x**2 + 5*y**2

In [18]:
def h(u):
    return 20*(10 - 2*u)

In [27]:
x = -2 * np.sqrt(2)
y = 1 + 2 * np.sqrt(2)
u = 15 + (5/(2 * np.sqrt(2)))

In [28]:
f(x, y)

153.2842712474619

In [29]:
h(u)

-470.71067811865476